# Generated by Django 2.0.5 on 2018-05-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180529_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card',
            field=models.CharField(default='default0000', max_length=50),
        ),
    ]
