# Generated by Django 2.0.5 on 2018-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180529_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=2234234, max_length=20),
            preserve_default=False,
        ),
    ]
